package com.theokanning.openai.ImageGenerations;

import com.theokanning.openai.completion.CompletionRequest;
import com.theokanning.openai.completion.LogProbResult;
import lombok.Data;

/**
 * A completion generated by GPT-3
 *
 * https://beta.openai.com/docs/api-reference/completions/create
 */
@Data
public class ImageGenerationsData {

    String url;


}
